apiVersion: apps/v1
kind: Deployment
metadata:
  name: whale-deploy
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello-whale
        image: veerendradevops/hellowhale
        ports:
        - containerPort: 80
    